/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ktfGPWbSHWLfyvQdjdTkkN
// Component: bjcya7kKeenj
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: ktfGPWbSHWLfyvQdjdTkkN/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: bjcya7kKeenj/css

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"iPhone13Mini13"}
            data-plasmic-override={overrides.iPhone13Mini13}
            className={classNames(projectcss.all, sty.iPhone13Mini13)}
          >
            <div
              data-plasmic-name={"rectangle17"}
              data-plasmic-override={overrides.rectangle17}
              className={classNames(projectcss.all, sty.rectangle17)}
            />

            <div
              data-plasmic-name={"_1748541"}
              data-plasmic-override={overrides._1748541}
              className={classNames(projectcss.all, sty._1748541)}
            />

            <div
              data-plasmic-name={"_7321901"}
              data-plasmic-override={overrides._7321901}
              className={classNames(projectcss.all, sty._7321901)}
            />

            <div
              data-plasmic-name={"_158869321"}
              data-plasmic-override={overrides._158869321}
              className={classNames(projectcss.all, sty._158869321)}
            />

            <div
              data-plasmic-name={"_59682921"}
              data-plasmic-override={overrides._59682921}
              className={classNames(projectcss.all, sty._59682921)}
            />

            <div
              data-plasmic-name={"_59683221"}
              data-plasmic-override={overrides._59683221}
              className={classNames(projectcss.all, sty._59683221)}
            />

            <div
              data-plasmic-name={"_59683501"}
              data-plasmic-override={overrides._59683501}
              className={classNames(projectcss.all, sty._59683501)}
            />

            <div
              data-plasmic-name={"_59683502"}
              data-plasmic-override={overrides._59683502}
              className={classNames(projectcss.all, sty._59683502)}
            />

            <div
              data-plasmic-name={"_146655201"}
              data-plasmic-override={overrides._146655201}
              className={classNames(projectcss.all, sty._146655201)}
            />

            <div
              data-plasmic-name={"_80997631"}
              data-plasmic-override={overrides._80997631}
              className={classNames(projectcss.all, sty._80997631)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wCy9Z
              )}
            >
              {"LogoName"}
            </div>
            <div
              data-plasmic-name={"_61885701"}
              data-plasmic-override={overrides._61885701}
              className={classNames(projectcss.all, sty._61885701)}
            />

            <div
              data-plasmic-name={"rectangle2"}
              data-plasmic-override={overrides.rectangle2}
              className={classNames(projectcss.all, sty.rectangle2)}
            />

            <div
              data-plasmic-name={"rectangle18"}
              data-plasmic-override={overrides.rectangle18}
              className={classNames(projectcss.all, sty.rectangle18)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ltMtn
              )}
            >
              {"Free Course \n(Beginner)"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mh2B0
              )}
            >
              {"Paid Course \n(Advanced)"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1Gjws
              )}
            >
              {"HTML"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qy63H
              )}
            >
              {"Python"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bzyR
              )}
            >
              {"PHP"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wcXol
              )}
            >
              {"CSS"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ygBKy
              )}
            >
              {"JavaScript"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "iPhone13Mini13",
    "rectangle17",
    "_1748541",
    "_7321901",
    "_158869321",
    "_59682921",
    "_59683221",
    "_59683501",
    "_59683502",
    "_146655201",
    "_80997631",
    "_61885701",
    "rectangle2",
    "rectangle18"
  ],

  iPhone13Mini13: [
    "iPhone13Mini13",
    "rectangle17",
    "_1748541",
    "_7321901",
    "_158869321",
    "_59682921",
    "_59683221",
    "_59683501",
    "_59683502",
    "_146655201",
    "_80997631",
    "_61885701",
    "rectangle2",
    "rectangle18"
  ],

  rectangle17: ["rectangle17"],
  _1748541: ["_1748541"],
  _7321901: ["_7321901"],
  _158869321: ["_158869321"],
  _59682921: ["_59682921"],
  _59683221: ["_59683221"],
  _59683501: ["_59683501"],
  _59683502: ["_59683502"],
  _146655201: ["_146655201"],
  _80997631: ["_80997631"],
  _61885701: ["_61885701"],
  rectangle2: ["rectangle2"],
  rectangle18: ["rectangle18"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iPhone13Mini13: makeNodeComponent("iPhone13Mini13"),
    rectangle17: makeNodeComponent("rectangle17"),
    _1748541: makeNodeComponent("_1748541"),
    _7321901: makeNodeComponent("_7321901"),
    _158869321: makeNodeComponent("_158869321"),
    _59682921: makeNodeComponent("_59682921"),
    _59683221: makeNodeComponent("_59683221"),
    _59683501: makeNodeComponent("_59683501"),
    _59683502: makeNodeComponent("_59683502"),
    _146655201: makeNodeComponent("_146655201"),
    _80997631: makeNodeComponent("_80997631"),
    _61885701: makeNodeComponent("_61885701"),
    rectangle2: makeNodeComponent("rectangle2"),
    rectangle18: makeNodeComponent("rectangle18"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
